In [32]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [33]:
df = pd.DataFrame({
    "soil_moisture" : [0.10, 0.15,0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                     0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c" : [34,30,26,22,28,30,19,22,35,24,33,33,21,25,20,29],

    "sunlight_hours" : [ 9,8,7,4,8,10,3,10,12,5,9,11,2,6,1,9],

    "needs_water" : [ 1,1,1,0,0,0,0,1,0,1,0,1,0,0,1,1 ]
})

In [34]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [35]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'],
      dtype='str')

In [36]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

### Scale the values.

In [37]:
X_min = X.min()
X_max = X.max()
X_scaled = ( X - X_min) / ( X_max - X_min + 1e-8 )

In [38]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [39]:
X_train, X_test, y_train, y_test = train_test_split( X_scaled,y,
                                    random_state=42, test_size=0.25)

### Train the model using keras

In [40]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)), # input layer 
    layers.Dense(8, activation= 'relu'), #hidden neurons
    layers.Dense(1,activation='sigmoid') # output layer 
])

In [41]:
model.compile(optimizer= 'sgd', loss = 'binary_crossentropy',metrics= ['accuracy'] )

In [43]:
history = model.fit(
    X_train.values, y_train.values,
    validation_data = (X_test.values, y_test.values),
    epochs = 100, batch_size = 4, verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.5927 - val_accuracy: 0.7500 - val_loss: 0.7251
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5920 - val_accuracy: 0.7500 - val_loss: 0.7250
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5913 - val_accuracy: 0.7500 - val_loss: 0.7249
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5906 - val_accuracy: 0.7500 - val_loss: 0.7248
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.5900 - val_accuracy: 0.7500 - val_loss: 0.7247
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5894 - val_accuracy: 0.7500 - val_loss: 0.7247
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5888 - val_accuracy: 0.7500 - val_loss: 0.7247
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5882 - val_accuracy: 0.7500 - val_loss: 0.7246
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.5876 - val_accuracy: 0.7500 - val_loss: 0.7246
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5870 - val_accuracy: 0.7500 - val_loss: 0.7245
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5865 - val_accuracy: 0.7500 - val_loss: 0.7245
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5859 - val_accuracy: 0.7500 - val_loss: 0.7244
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.5853 - val_accuracy: 0.7500 - val_loss: 0.7244
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.5847 - val_accuracy: 0.7500 - val_loss: 0.7243
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.5841 - val_accuracy: 0.7500 - val_loss: 0.7242
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5835 - val_accuracy: 0.7500 - val_loss: 0.7241
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5830 - val_accuracy: 0.7500 - val_loss: 0.7241
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5824 - val_accuracy: 0.7500 - val_loss: 0.7240
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.5818 - val_accuracy: 0.7500 - val_loss: 0.7239
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.5812 - val_accuracy: 0.7500 - val_loss: 0.7238
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6667 - loss: 0.5806 - val_accuracy: 0.7500 - val_loss: 0.7237
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6667 - loss: 0.5800 - val_accuracy: 0.7500 - val_loss: 0.7236
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.5795 - val_accuracy: 0.7500 - val_loss: 0.7235
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6667 - loss: 0.5789 - val_accuracy: 0.7500 - val_loss: 0.7234
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5783 - val_accuracy: 0.7500 - val_loss: 0.7233
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5777 - val_accuracy: 0.7500 - val_loss: 0.7232
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5771 - val_accuracy: 0.7500 - val_loss: 0.7230
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5765 - val_accuracy: 0.7500 - val_loss: 0.7229
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5759 - val_accuracy: 0.7500 - val_loss: 0.7227
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5754 - val_accuracy: 0.7500 - val_loss: 0.7226
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5748 - val_accuracy: 0.7500 - val_loss: 0.7224
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5742 - val_accuracy: 0.7500 - val_loss: 0.7223
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.5736 - val_accuracy: 0.7500 - val_loss: 0.7222
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5730 - val_accuracy: 0.7500 - val_loss: 0.7220
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5724 - val_accuracy: 0.7500 - val_loss: 0.7219
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5718 - val_accuracy: 0.7500 - val_loss: 0.7217
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.5713 - val_accuracy: 0.7500 - val_loss: 0.7215
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6667 - loss: 0.5707 - val_accuracy: 0.7500 - val_loss: 0.7214
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5701 - val_accuracy: 0.7500 - val_loss: 0.7212
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5694 - val_accuracy: 0.7500 - val_loss: 0.7210
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5689 - val_accuracy: 0.7500 - val_loss: 0.7208
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.5683 - val_accuracy: 0.7500 - val_loss: 0.7206
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5677 - val_accuracy: 0.7500 - val_loss: 0.7204
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.5671 - val_accuracy: 0.7500 - val_loss: 0.7203
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5665 - val_accuracy: 0.7500 - val_loss: 0.7201
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5659 - val_accuracy: 0.7500 - val_loss: 0.7199
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5653 - val_accuracy: 0.7500 - val_loss: 0.7196
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5648 - val_accuracy: 0.7500 - val_loss: 0.7194
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5642 - val_accuracy: 0.7500 - val_loss: 0.7192
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5636 - val_accuracy: 0.7500 - val_loss: 0.7190
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.5630 - val_accuracy: 0.7500 - val_loss: 0.7188
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5624 - val_accuracy: 0.7500 - val_loss: 0.7186
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5617 - val_accuracy: 0.7500 - val_loss: 0.7183
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5612 - val_accuracy: 0.7500 - val_loss: 0.7181
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.5606 - val_accuracy: 0.7500 - val_loss: 0.7179
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5600 - val_accuracy: 0.7500 - val_loss: 0.7176
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.5594 - val_accuracy: 0.7500 - val_loss: 0.7174
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5588 - val_accuracy: 0.7500 - val_loss: 0.7171
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5583 - val_accuracy: 0.7500 - val_loss: 0.7169
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5577 - val_accuracy: 0.7500 - val_loss: 0.7166
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5570 - val_accuracy: 0.7500 - val_loss: 0.7164
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5564 - val_accuracy: 0.7500 - val_loss: 0.7161
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5558 - val_accuracy: 0.7500 - val_loss: 0.7158
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.5553 - val_accuracy: 0.7500 - val_loss: 0.7155
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5547 - val_accuracy: 0.7500 - val_loss: 0.7152
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5541 - val_accuracy: 0.7500 - val_loss: 0.7149
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5534 - val_accuracy: 0.7500 - val_loss: 0.7146
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5529 - val_accuracy: 0.7500 - val_loss: 0.7143
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5522 - val_accuracy: 0.7500 - val_loss: 0.7141
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5516 - val_accuracy: 0.7500 - val_loss: 0.7138
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5510 - val_accuracy: 0.7500 - val_loss: 0.7135
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5503 - val_accuracy: 0.7500 - val_loss: 0.7132
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5497 - val_accuracy: 0.7500 - val_loss: 0.7129
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5491 - val_accuracy: 0.7500 - val_loss: 0.7127
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5484 - val_accuracy: 0.7500 - val_loss: 0.7123
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.5478 - val_accuracy: 0.7500 - val_loss: 0.7121
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5471 - val_accuracy: 0.7500 - val_loss: 0.7118
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5465 - val_accuracy: 0.7500 - val_loss: 0.7116
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.5457 - val_accuracy: 0.7500 - val_loss: 0.7113
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.5451 - val_accuracy: 0.7500 - val_loss: 0.7110
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5444 - val_accuracy: 0.7500 - val_loss: 0.7107
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.5437 - val_accuracy: 0.7500 - val_loss: 0.7105
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.5430 - val_accuracy: 0.7500 - val_loss: 0.7102
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.5424 - val_accuracy: 0.7500 - val_loss: 0.7099
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5417 - val_accuracy: 0.7500 - val_loss: 0.7096
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5410 - val_accuracy: 0.7500 - val_loss: 0.7093
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.5404 - val_accuracy: 0.7500 - val_loss: 0.7090
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5397 - val_accuracy: 0.7500 - val_loss: 0.7087
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5389 - val_accuracy: 0.7500 - val_loss: 0.7084
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 0.5384 - val_accuracy: 0.7500 - val_loss: 0.7081
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7500 - loss: 0.5377 - val_accuracy: 0.7500 - val_loss: 0.7078
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 0.5369 - val_accuracy: 0.7500 - val_loss: 0.7074
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5363 - val_accuracy: 0.7500 - val_loss: 0.7071
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 0.5356 - val_accuracy: 0.7500 - val_loss: 0.7068
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 0.5349 - val_accuracy: 0.7500 - val_loss: 0.7064
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7500 - loss: 0.5343 - val_accuracy: 0.7500 - val_loss: 0.7061
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 0.5336 - val_accuracy: 0.7500 - val_loss: 0.7059
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 0.5329 - val_accuracy: 0.7500 - val_loss: 0.7057
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5323 - val_accuracy: 0.7500 - val_loss: 0.7055
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.5317 - val_accuracy: 0.7500 - val_loss: 0.7053

* loss & accuracy = how well model is doing on training data. 

* val_loss & val_accuracy = how well model is doing on new unseen data.

1. loss

    This is a training loss. 
    
    It tells you how wrong your model's prediction are on the training set, according to the loss funciton you chose (in your case: binary cross-entropy)

    Lower is better. 
    
    During training the model tried to reduce this number by updating weights with gradient descent.

2. accuracy

    This is the training accuracy. 

    It tell you what fraction of training samples the model is correctly predicting. 
    
    Ex: if you have 100 samples and the model gets 80 correct -> accuracy=0.80% (80%)

3. val_loss 

    This is the validation loss. 

    After generalizing well or just memorizing set(the split you gave with validation_data=...) and calculates the loss on that unseen data. 

    This tells you whether your model is generalizing well or just memorizing the training data.

4. val_accuracy 

    This is the validation accuracy. 

    It's the percentage of correct predictions on the validation set. 

    If accuracy is high but val_accuracy is low -> your model is probably overfitting (memorizing training but failing on new data).